Fix deployment location referenced in the generated test results
w3c/wptreport pull request #29
Opened 2024-09-27 16:26 UTC by anssiko

w3c-tests.org -> wpt.live

This fixes corresponding links in the generated test results, wpt.live is where the test suites are deployed nowadays.

2024-09-27 17:13 UTC, gsnedders requested changes
These should still all be `http`; tests run over `http` by default unless they opt-in to a secure origin.

2024-09-27 17:33 UTC, anssiko commented
@gsnedders thanks for your swift review, PR updated.

2024-09-27 18:46 UTC, gsnedders requested changes

2024-09-27 18:46 UTC, gsnedders commented on index.js
> +        table += "<tr class='test' id='test-file-" + test.testNum + "'><td><a href='https://wpt.live" + esc(test.name) + "' target='_blank'>" +
```suggestion
        table += "<tr class='test' id='test-file-" + test.testNum + "'><td><a href='http://wpt.live" + esc(test.name) + "' target='_blank'>" +
```

2024-09-27 18:46 UTC, gsnedders commented on index.js
> +        table += "<tr class='test' id='test-file-" + test.testNum + "'><td><a href='https://wpt.live" + esc(test.name) + "' target='_blank'>" +
```suggestion
        table += "<tr class='test' id='test-file-" + test.testNum + "'><td><a href='http://wpt.live" + esc(test.name) + "' target='_blank'>" +
```

2024-10-01 00:14 UTC, gsnedders approved these changes

2024-10-01 00:15 UTC, merged